server:
    port: 8082
    servlet:
      context-path: /ims
spring:
  application:
    name: FoodIMS
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foodims?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
#  web:
#    resources:
#      static-locations: classpath:/static
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true